/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_luoyi_luoyipublisher_MotionDetectionJNI */

#ifndef _Included_com_luoyi_luoyipublisher_MotionDetectionJNI
#define _Included_com_luoyi_luoyipublisher_MotionDetectionJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_luoyi_luoyipublisher_MotionDetectionJNI
 * Method:    diffCalcu
 * Signature: ([I[I[III)V
 */
JNIEXPORT void JNICALL Java_com_luoyi_luoyipublisher_MotionDetectionJNI_diffCalcu
  (JNIEnv *, jobject, jintArray, jintArray, jintArray, jint, jint);

/*
 * Class:     com_luoyi_luoyipublisher_MotionDetectionJNI
 * Method:    seekIntersection
 * Signature: ([I[I[III)V
 */
JNIEXPORT void JNICALL Java_com_luoyi_luoyipublisher_MotionDetectionJNI_seekIntersection
  (JNIEnv *, jobject, jintArray, jintArray, jintArray, jint, jint);

JNIEXPORT void JNICALL Java_com_luoyi_luoyipublisher_MotionDetectionJNI_threeFrameDiff
        (JNIEnv *env, jobject job, jintArray firstFame, jintArray secondFrame, jintArray thirdFrame, jintArray buff, jint width, jint height);

JNIEXPORT void JNICALL Java_com_luoyi_luoyipublisher_MotionDetectionJNI_drawMinRect
        (JNIEnv *env, jobject srcBitmap, jintArray buff);

JNIEXPORT void JNICALL Java_com_luoyi_luoyipublisher_MotionDetectionJNI_drawMonitorArea
        (JNIEnv *env, jobject job, jintArray pixels, jint width, jint height, jint left, jint top, jint right, jint bottom);
#ifdef __cplusplus
}
#endif
#endif
